### ISSUE TITLE
Tiago Simulation Controllers not working in ROS 2 Humble and gazebo

### ISSUE THREAD

**Issue by nilutpolkashyap** [pal-robotics/tiago_simulation#28] opened 2024-01-13 12:28 UTC
### Issue: Tiago Simulation ROS 2 humble branch does not move any of its joints. 

I was previously able to solve this issue here by just cloning the ros2_control humble branch and gazebo_ros2_control humble branch in my workspace and building them. Here is my previous issue #22 

But now, I am repeating the same steps but now the controllers are not working. I am not able to control the simulation using keyboard.

**System Specs**
1. Ubuntu 22.04
2. Gazebo Classic 11
3. ROS 2 Humble

**Steps I Followed**
1. Cloned [tiago_simulation](https://github.com/pal-robotics/tiago_simulation/tree/humble-devel) humble branch
2. git clone https://github.com/ros-controls/ros2_control.git -b humble 
3. git clone https://github.com/ros-controls/gazebo_ros2_control.git -b humble
4. git clone https://github.com/pal-robotics/pal_hey5.git -b humble-devel
5. git clone https://github.com/ros-perception/vision_msgs.git -b ros2
6. git clone https://github.com/pal-robotics/play_motion2.git -b humble-devel
7. git clone https://github.com/PickNikRobotics/launch_param_builder.git 
8. git clone https://github.com/pal-robotics/pal_urdf_utils.git -b humble-devel

I am trying to launch Tiago robot simulation in Gazebo Classic using 
```ros2 launch tiago_gazebo tiago_gazebo.launch.py arm:=no-arm```

Terminal Output (with Error)
```
[robot_state_publisher-12] [INFO] [1705147635.308914566] [robot_state_publisher]: got segment caster_front_left_2_link
[robot_state_publisher-12] [INFO] [1705147635.308925948] [robot_state_publisher]: got segment caster_front_right_1_link
[robot_state_publisher-12] [INFO] [1705147635.308941278] [robot_state_publisher]: got segment caster_front_right_2_link
[robot_state_publisher-12] [INFO] [1705147635.308953569] [robot_state_publisher]: got segment head_1_link
[robot_state_publisher-12] [INFO] [1705147635.308966719] [robot_state_publisher]: got segment head_2_link
[robot_state_publisher-12] [INFO] [1705147635.308978541] [robot_state_publisher]: got segment head_front_camera_depth_frame
[robot_state_publisher-12] [INFO] [1705147635.308990281] [robot_state_publisher]: got segment head_front_camera_depth_optical_frame
[robot_state_publisher-12] [INFO] [1705147635.309004789] [robot_state_publisher]: got segment head_front_camera_link
[robot_state_publisher-12] [INFO] [1705147635.309016572] [robot_state_publisher]: got segment head_front_camera_optical_frame
[robot_state_publisher-12] [INFO] [1705147635.309028213] [robot_state_publisher]: got segment head_front_camera_orbbec_aux_joint_frame
[robot_state_publisher-12] [INFO] [1705147635.309039775] [robot_state_publisher]: got segment head_front_camera_rgb_frame
[robot_state_publisher-12] [INFO] [1705147635.309051434] [robot_state_publisher]: got segment head_front_camera_rgb_optical_frame
[robot_state_publisher-12] [INFO] [1705147635.309062939] [robot_state_publisher]: got segment rgbd_laser_link
[robot_state_publisher-12] [INFO] [1705147635.309074355] [robot_state_publisher]: got segment suspension_left_link
[robot_state_publisher-12] [INFO] [1705147635.309085796] [robot_state_publisher]: got segment suspension_right_link
[robot_state_publisher-12] [INFO] [1705147635.309097577] [robot_state_publisher]: got segment torso_fixed_column_link
[robot_state_publisher-12] [INFO] [1705147635.309108986] [robot_state_publisher]: got segment torso_fixed_link
[robot_state_publisher-12] [INFO] [1705147635.309120497] [robot_state_publisher]: got segment torso_lift_link
[robot_state_publisher-12] [INFO] [1705147635.309131912] [robot_state_publisher]: got segment wheel_left_link
[robot_state_publisher-12] [INFO] [1705147635.309143308] [robot_state_publisher]: got segment wheel_right_link
[spawn_entity.py-3] [INFO] [1705147636.134563543] [spawn_entity]: Spawn Entity started
[spawn_entity.py-3] [INFO] [1705147636.135440982] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-3] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-3]   warnings.warn(
[spawn_entity.py-3] [INFO] [1705147636.440675382] [spawn_entity]: Waiting for entity xml on robot_description
[spawn_entity.py-3] [INFO] [1705147636.638303328] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-3] [INFO] [1705147636.639161423] [spawn_entity]: Waiting for service /spawn_entity
[spawn_entity.py-3] [INFO] [1705147637.647572551] [spawn_entity]: Calling service /spawn_entity
[spawner-5] [INFO] [1705147637.837050264] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1705147638.075292623] [spawner_head_controller]: Waiting for '/controller_manager' node to exist
[gzserver-1] [INFO] [1705147638.322908527] [base_imu]: <initial_orientation_as_reference> is unset, using default value of false to comply with REP 145 (world as orientation reference)
[spawner-6] [INFO] [1705147638.621901077] [spawner_torso_controller]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1705147638.689680166] [spawner_mobile_base_controller]: Waiting for '/controller_manager' node to exist
[spawn_entity.py-3] [INFO] [1705147638.860202921] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [tiago]
[INFO] [spawn_entity.py-3]: process has finished cleanly [pid 19506]
[gzserver-1] [INFO] [1705147639.711306066] [head_front_camera_frame_controller]: Publishing camera info to [/head_front_camera/rgb/camera_info]
[gzserver-1] [INFO] [1705147639.713488610] [head_front_camera_frame_controller]: Publishing depth camera info to [/head_front_camera/depth_registered/camera_info]
[gzserver-1] [INFO] [1705147639.715055198] [head_front_camera_frame_controller]: Publishing pointcloud to [/head_front_camera/depth_registered/points]
[spawner-5] [INFO] [1705147639.859204517] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[gzserver-1] [INFO] [1705147639.867468382] [gazebo_ros2_control]: Loading gazebo_ros2_control plugin
[gzserver-1] [INFO] [1705147639.895916386] [gazebo_ros2_control]: Starting gazebo_ros2_control plugin in namespace: /
[gzserver-1] [INFO] [1705147639.896004483] [gazebo_ros2_control]: Starting gazebo_ros2_control plugin in ros 2 node: gazebo_ros2_control
[gzserver-1] [INFO] [1705147639.899481841] [gazebo_ros2_control]: Loading parameter files /home/ubuntu/bookros2_ws/install/tiago_controller_configuration/share/tiago_controller_configuration/config/gazebo_controller_manager_cfg.yaml
[gzserver-1] [INFO] [1705147639.926343223] [gazebo_ros2_control]: connected to service!! robot_state_publisher
[gzserver-1] [INFO] [1705147639.940658292] [gazebo_ros2_control]: Received urdf from param server, parsing...
[gzserver-1] [INFO] [1705147640.014135873] [gazebo_ros2_control]: Loading joint: wheel_right_joint
[gzserver-1] [INFO] [1705147640.014408075] [gazebo_ros2_control]: 	State:
[gzserver-1] [INFO] [1705147640.014518447] [gazebo_ros2_control]: 		 position
[gzserver-1] [INFO] [1705147640.015407839] [gazebo_ros2_control]: 	Command:
[gzserver-1] [INFO] [1705147640.015540227] [gazebo_ros2_control]: 		 velocity
[gzserver-1] [INFO] [1705147640.016125786] [gazebo_ros2_control]: Loading joint: wheel_left_joint
[gzserver-1] [INFO] [1705147640.016151402] [gazebo_ros2_control]: 	State:
[gzserver-1] [INFO] [1705147640.016167065] [gazebo_ros2_control]: 		 position
[gzserver-1] [INFO] [1705147640.016374626] [gazebo_ros2_control]: 	Command:
[gzserver-1] [INFO] [1705147640.016408476] [gazebo_ros2_control]: 		 velocity
[gzserver-1] [INFO] [1705147640.016615000] [gazebo_ros2_control]: Loading joint: torso_lift_joint
[gzserver-1] [INFO] [1705147640.016647748] [gazebo_ros2_control]: 	State:
[gzserver-1] [INFO] [1705147640.016664334] [gazebo_ros2_control]: 		 position
[gzserver-1] [INFO] [1705147640.016688868] [gazebo_ros2_control]: 		 velocity
[gzserver-1] [INFO] [1705147640.016707654] [gazebo_ros2_control]: 		 effort
[gzserver-1] [INFO] [1705147640.016796637] [gazebo_ros2_control]: 	Command:
[gzserver-1] [INFO] [1705147640.016816636] [gazebo_ros2_control]: 		 position
[gzserver-1] [INFO] [1705147640.016903425] [gazebo_ros2_control]: Loading joint: head_1_joint
[gzserver-1] [INFO] [1705147640.016924448] [gazebo_ros2_control]: 	State:
[gzserver-1] [INFO] [1705147640.016939466] [gazebo_ros2_control]: 		 position
[gzserver-1] [INFO] [1705147640.016955695] [gazebo_ros2_control]: 		 velocity
[gzserver-1] [INFO] [1705147640.016974946] [gazebo_ros2_control]: 		 effort
[gzserver-1] [INFO] [1705147640.017033551] [gazebo_ros2_control]: 	Command:
[gzserver-1] [INFO] [1705147640.017057794] [gazebo_ros2_control]: 		 position
[gzserver-1] [INFO] [1705147640.017095314] [gazebo_ros2_control]: Loading joint: head_2_joint
[gzserver-1] [INFO] [1705147640.017118725] [gazebo_ros2_control]: 	State:
[gzserver-1] [INFO] [1705147640.017134371] [gazebo_ros2_control]: 		 position
[gzserver-1] [INFO] [1705147640.017159614] [gazebo_ros2_control]: 		 velocity
[gzserver-1] [INFO] [1705147640.017177251] [gazebo_ros2_control]: 		 effort
[gzserver-1] [INFO] [1705147640.017193340] [gazebo_ros2_control]: 	Command:
[gzserver-1] [INFO] [1705147640.017208284] [gazebo_ros2_control]: 		 position
[gzserver-1] [INFO] [1705147640.019334013] [gazebo_ros2_control]: Loading sensor: base_imu_sensor
[gzserver-1] [INFO] [1705147640.019378953] [gazebo_ros2_control]: 	State:
[gzserver-1] [INFO] [1705147640.020220347] [gazebo_ros2_control]: 		 orientation.x
[gzserver-1] [INFO] [1705147640.020513032] [gazebo_ros2_control]: 		 orientation.y
[gzserver-1] [INFO] [1705147640.020538297] [gazebo_ros2_control]: 		 orientation.z
[gzserver-1] [INFO] [1705147640.020570886] [gazebo_ros2_control]: 		 orientation.w
[gzserver-1] [INFO] [1705147640.020591112] [gazebo_ros2_control]: 		 angular_velocity.
[gzserver-1] [INFO] [1705147640.020608522] [gazebo_ros2_control]: 		 angular_velocity.y
[gzserver-1] [INFO] [1705147640.020659082] [gazebo_ros2_control]: 		 angular_velocity.z
[gzserver-1] [INFO] [1705147640.020694674] [gazebo_ros2_control]: 		 linear_acceleration.x
[gzserver-1] [INFO] [1705147640.020800397] [gazebo_ros2_control]: 		 linear_acceleration.y
[gzserver-1] [INFO] [1705147640.020829727] [gazebo_ros2_control]: 		 linear_acceleration.z
[gzserver-1] [INFO] [1705147640.021875344] [resource_manager]: Initialize hardware 'ros2_control_tiago_system' 
[gzserver-1] [INFO] [1705147640.023880449] [resource_manager]: Successful initialization of hardware 'ros2_control_tiago_system'
[gzserver-1] [INFO] [1705147640.028177804] [resource_manager]: 'configure' hardware 'ros2_control_tiago_system' 
[gzserver-1] [INFO] [1705147640.028346963] [resource_manager]: Successful 'configure' of hardware 'ros2_control_tiago_system'
[gzserver-1] [INFO] [1705147640.028548842] [resource_manager]: 'activate' hardware 'ros2_control_tiago_system' 
[gzserver-1] [INFO] [1705147640.028565810] [resource_manager]: Successful 'activate' of hardware 'ros2_control_tiago_system'
[gzserver-1] [INFO] [1705147640.029340769] [gazebo_ros2_control]: Loading controller_manager
[spawner-7] [INFO] [1705147640.093897587] [spawner_head_controller]: Waiting for '/controller_manager' services to be available
[gzserver-1] [INFO] [1705147640.115399973] [controller_manager]: Subscribing to '~/robot_description' topic for robot description file.
[gzserver-1] [WARN] [1705147640.132949307] [gazebo_ros2_control]:  Desired controller update period (0.01 s) is slower than the gazebo simulation period (0.001 s).
[gzserver-1] [INFO] [1705147640.135670400] [gazebo_ros2_control]: Loaded gazebo_ros2_control.
[spawner-6] [INFO] [1705147640.645595664] [spawner_torso_controller]: Waiting for '/controller_manager' services to be available
[spawner-4] [INFO] [1705147640.722148007] [spawner_mobile_base_controller]: Waiting for '/controller_manager' services to be available
[play_motion2_node-8] [ERROR] [1705147640.723948540] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147640.724648205] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147640.830328041] [arm_tucker]: play_motion2 is not ready
[spawner-5] [INFO] [1705147641.879654762] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' services to be available
[spawner-7] [INFO] [1705147642.117506975] [spawner_head_controller]: Waiting for '/controller_manager' services to be available
[spawner-6] [INFO] [1705147642.665497086] [spawner_torso_controller]: Waiting for '/controller_manager' services to be available
[spawner-4] [INFO] [1705147642.758809024] [spawner_mobile_base_controller]: Waiting for '/controller_manager' services to be available
[spawner-5] [INFO] [1705147643.902911657] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' services to be available
[spawner-7] [INFO] [1705147644.150166472] [spawner_head_controller]: Waiting for '/controller_manager' services to be available
[spawner-6] [INFO] [1705147644.685348181] [spawner_torso_controller]: Waiting for '/controller_manager' services to be available
[spawner-4] [INFO] [1705147644.795156763] [spawner_mobile_base_controller]: Waiting for '/controller_manager' services to be available
[play_motion2_node-8] [ERROR] [1705147644.835288621] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147644.835453227] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147644.837543603] [arm_tucker]: play_motion2 is not ready
[spawner-5] [ERROR] [1705147645.923144095] [spawner_joint_state_broadcaster]: Controller manager not available
[spawner-7] [ERROR] [1705147646.165562160] [spawner_head_controller]: Controller manager not available
[ERROR] [spawner-5]: process has died [pid 19510, exit code 1, cmd '/home/ubuntu/bookros2_ws/install/controller_manager/lib/controller_manager/spawner joint_state_broadcaster --controller-manager controller_manager --controller-type joint_state_broadcaster/JointStateBroadcaster --param-file /home/ubuntu/bookros2_ws/install/tiago_controller_configuration/share/tiago_controller_configuration/config/joint_state_broadcaster.yaml --ros-args'].
[ERROR] [spawner-7]: process has died [pid 19517, exit code 1, cmd '/home/ubuntu/bookros2_ws/install/controller_manager/lib/controller_manager/spawner head_controller --controller-manager controller_manager --controller-type joint_trajectory_controller/JointTrajectoryController --param-file /home/ubuntu/bookros2_ws/install/tiago_controller_configuration/share/tiago_controller_configuration/config/head_controller.yaml --ros-args'].
[spawner-4] [ERROR] [1705147646.613717754] [spawner_mobile_base_controller]: Controller manager not available
[spawner-6] [ERROR] [1705147646.711370694] [spawner_torso_controller]: Controller manager not available
[ERROR] [spawner-4]: process has died [pid 19508, exit code 1, cmd '/home/ubuntu/bookros2_ws/install/controller_manager/lib/controller_manager/spawner mobile_base_controller --controller-manager controller_manager --controller-type diff_drive_controller/DiffDriveController --param-file /home/ubuntu/bookros2_ws/install/tiago_controller_configuration/share/tiago_controller_configuration/config/mobile_base_controller.yaml --ros-args'].
[ERROR] [spawner-6]: process has died [pid 19514, exit code 1, cmd '/home/ubuntu/bookros2_ws/install/controller_manager/lib/controller_manager/spawner torso_controller --controller-manager controller_manager --controller-type joint_trajectory_controller/JointTrajectoryController --param-file /home/ubuntu/bookros2_ws/install/tiago_controller_configuration/share/tiago_controller_configuration/config/torso_controller.yaml --ros-args'].
[play_motion2_node-8] [ERROR] [1705147648.841029599] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147648.841279375] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147648.844376169] [arm_tucker]: play_motion2 is not ready
[play_motion2_node-8] [ERROR] [1705147652.846151322] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147652.846267873] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147652.849892027] [arm_tucker]: play_motion2 is not ready
[play_motion2_node-8] [ERROR] [1705147656.853824317] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147656.853915841] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147656.856767980] [arm_tucker]: play_motion2 is not ready
[play_motion2_node-8] [ERROR] [1705147660.858620834] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147660.858705513] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147660.859982520] [arm_tucker]: play_motion2 is not ready
[play_motion2_node-8] [ERROR] [1705147664.863957409] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147664.864083452] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147664.866472204] [arm_tucker]: play_motion2 is not ready
[play_motion2_node-8] [ERROR] [1705147668.868487275] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147668.868566720] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147668.869709813] [arm_tucker]: play_motion2 is not ready
[play_motion2_node-8] [ERROR] [1705147672.873548943] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147672.873652845] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147672.875283442] [arm_tucker]: play_motion2 is not ready
[play_motion2_node-8] [ERROR] [1705147676.878690298] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147676.878863132] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147676.885502266] [arm_tucker]: play_motion2 is not ready
[play_motion2_node-8] [ERROR] [1705147680.893137080] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147680.893235422] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147680.894898665] [arm_tucker]: play_motion2 is not ready
[play_motion2_node-8] [ERROR] [1705147684.903039343] [play_motion2]: Service /controller_manager/list_controllers not available.
[play_motion2_node-8] [ERROR] [1705147684.903175367] [play_motion2]: There are no active JointTrajectory controllers available
[tuck_arm.py-13] [ERROR] [1705147684.904305059] [arm_tucker]: play_motion2 is not ready
```

![tiago_error1](https://github.com/pal-robotics/tiago_simulation/assets/47447024/f3be8606-9e7e-4fbc-b59b-0e1c92e5ee0c)

![tiago_error2](https://github.com/pal-robotics/tiago_simulation/assets/47447024/f947e5e4-03c7-41f7-8a6d-83919879f9c9)

Even if I try to move the robot, I get nothing, no movement
```ros2 topic pub /mobile_base_controller/cmd_vel_unstamped geometry_msgs/msg/Twist '{linear: {x: 1}, angular: {z: 0}}' -r10```

![tiago_error3](https://github.com/pal-robotics/tiago_simulation/assets/47447024/84e1e063-0b7d-45cf-9e55-e8ee113be0c1)

Please help me out. Thank you

**Comment by nilutpolkashyap** [comment] 2024-01-16 06:08
Hi @Noel215 , any help would be appreciated

**Comment by Noel215** [comment] 2024-01-16 10:45
Hi @nilutpolkashyap,

It stopped working after they merged https://github.com/ros-controls/ros2_control/pull/1272 4 days ago.
I just opened an issue in the `ros2_control` repository.

For now you can checkout your local repository to the latest tag to make it work
```
git checkout 2.36.1
```

I hope that resolves your problem.

**Comment by nilutpolkashyap** [comment] 2024-01-17 12:26
Hi @Noel215 
I checkout out version 2.36.1 but I am again getting the following error. 
![Screenshot from 2024-01-17 17-55-11](https://github.com/pal-robotics/tiago_simulation/assets/47447024/8724ffc6-2ca4-4ec1-9435-20b1409a529c)
![Screenshot from 2024-01-17 17-54-57](https://github.com/pal-robotics/tiago_simulation/assets/47447024/432a102f-5988-43f4-a6ab-eac77c2fe5b1)


I also tried out different versions of ```ros2_control``` and ```gazebo_ros2_control``` but I still get the same error

**Comment by Noel215** [comment] 2024-01-17 12:37
If you clone the latest version of `ros2_controllers` it should work. I provided a fix for that in https://github.com/ros-controls/ros2_controllers/pull/968.

For more information see https://github.com/ros-controls/ros2_controllers/issues/966.

**Comment by saikishor** [comment] 2024-01-24 11:33
hello!

It will be solved with the upcoming sync: https://discourse.ros.org/t/preparing-for-humble-sync-and-patch-release-2024-01-26/35765

Thank you for your patience

Best Regards,
PAL Robotics Team

**Comment by gstavrinos** [comment] 2024-02-07 20:10
Just as a heads-up, I am experiencing the same issue with all the latest releases (checkout from source ros2_controllers, gazebo_ros2_control, ros2_control along with all the latest humble releases of your packages).

Any insight would be highly appreciated!


Edit: Issue https://github.com/pal-robotics/tiago_simulation/issues/29 also applies to me, but since it is still open, I guess it is being tracked, and that's why I did not mention it.

**Comment by saikishor** [comment] 2024-02-07 20:18
Hello @gstavrinos !

This has been recently reviewed and fixed. It should work. If it isn't, please send us more information to reproduce it. Try with the binaries installed, instead of compiling from source. We hope it helps.

Best regards,
PAL Robotics Team

**Comment by gstavrinos** [comment] 2024-02-07 20:20
Hey @saikishor,

Thank you for your quick reply. I tried both with the binaries and from source with the exact same results. I can provide you with whatever information you may ask, but I basically face the exact same error specified in this issue (missing controller manager).

**Comment by saikishor** [comment] 2024-02-07 20:22
Thanks for the prompt reply.  Can you please share the versions of the above packages and also hardware_interface and controller_mansger?

Thank you,

Best regards,
PAL Robotics Team

**Comment by gstavrinos** [comment] 2024-02-07 20:38
Here you are:

* `gazebo_ros2_control`: `0.4.6`
* `hardware_interface`: `2.38.0`
* `controller_manager`: `2.38.0`
* `ros2_controllers`: `2.32.0`
* `ros2_control`: `2.38.0`
---
* `tiago_moveit_config`: `3.0.9`
* `tiago_navigation`: `4.0.10`
* `tiago_gazebo`: `4.0.9`
* `tiago_robot`: `4.2.2`
---
* `play_motion2`: `0.0.15`
* `launch_pal`: `0.0.18`
---
* `pal_gazebo_worlds`: `4.0.3`
* `pal_urdf_utils`: `2.0.1`
---

I understand that some of there are most probably irrelevant, but I guess "excessive" information would not hurt!

**Comment by Noel215** [comment] 2024-02-12 09:16
Hi @gstavrinos,

The latest released versions are working, you don't need to have a workspace.
Just open a new environment (e.g. docker) and run:
`sudo apt update`
`sudo apt install ros-humble-tiago-simulation`

In case you want to have it in your workspace here you have the latest release for each repository on `humble`:

---
- `ros2_control`: `2.37.0`
- `ros2_controllers`: `2.32.0`
- `gazebo_ros2_control`: `0.4.6`
---
- `tiago_moveit_config`: `3.0.7`
- `tiago_nav`: `4.0.9`
- `tiago_robot`: `4.1.2`
- `tiago_simulation`: `4.0.8`
---
- `play_motion2`: `0.0.13`
- `launch_pal`: `0.0.16`
---
- `pal_gazebo_worlds`: `4.0.3`
- `pal_urdf_utils`: `2.0.1`
---

Let us know, please.

**Comment by gstavrinos** [comment] 2024-02-12 19:03
Hello @Noel215,

Thanks for getting back to me with such a detailed answer. I will test it and reply with my feedback asap. I plan on doing this in the next few days. 

Thanks again!

**Comment by nilutpolkashyap** [comment] 2024-02-12 23:20
Hi @Noel215 , 
Your previous solutions helped me to solve the robot's control problem with teleop. I was able to drive the robot. 

But today I checked the robot's head joints and also tried to use the moveit demos as shown [here](https://github.com/pal-robotics/tiago_simulation?tab=readme-ov-file#simulation--moveit-2) , none of the joints worked. I am not able to control any of the joints. When I try to execute the trajectory, the Moveit example shows me a "Failed" message in Rviz2.

Any help would be appreciated

**Comment by Noel215** [comment] 2024-02-13 08:04
Hi @nilutpolkashyap,

I've just tested it in a fresh `humble` docker with the debian installation and everything is working for me:
```
sudo apt install ros-humble-tiago-simulation
```
I've tried with some random valid trajectories.

Please, try it in the same way and if it's still not working give us more details in order to reproduce the issue.

**Comment by gstavrinos** [comment] 2024-02-20 18:26
I am getting back to this, just to confirm that, indeed, a completely fresh installation of the binary packages works without problems. Thank you!

**Comment by saikishor** [comment] 2024-02-20 18:30
Thank you for confirming it. I'll go ahead and close the issue

**Closed as completed** 2024-02-20 18:30 UTC
